<a href="https://colab.research.google.com/github/leoanholetto1/Data-Science/blob/main/Projeto3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip -q install plotly --upgrade

     |████████████████████████████████| 15.3 MB 31.3 MB/s 


In [2]:
import plotly.express as px
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
base_risco_credit = pd.read_csv('/content/risco_credito.csv')

In [5]:
base_risco_credit

historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12           boa   alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto

In [12]:
x_base_risco_credito = base_risco_credit.iloc[:,0:4].values
y_base_risco_credito = base_risco_credit.iloc[:,4].values

In [13]:
x_base_risco_credito

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [14]:
from sklearn.preprocessing import LabelEncoder
label_encoder_historia = LabelEncoder()
label_encoder_divida = LabelEncoder()
label_encoder_garantia = LabelEncoder()
label_encoder_renda = LabelEncoder()

In [15]:
x_base_risco_credito[:,0] = label_encoder_historia.fit_transform(x_base_risco_credito[:,0])
x_base_risco_credito[:,1] = label_encoder_divida.fit_transform(x_base_risco_credito[:,1])
x_base_risco_credito[:,2] = label_encoder_garantia.fit_transform(x_base_risco_credito[:,2])
x_base_risco_credito[:,3] = label_encoder_renda.fit_transform(x_base_risco_credito[:,3])

In [16]:
x_base_risco_credito

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [19]:
import pickle 
with open('risco_credito.pkl','wb') as f:
  pickle.dump([x_base_risco_credito,y_base_risco_credito],f)

In [18]:
from sklearn.naive_bayes import GaussianNB

In [21]:
naive_risco_credito = GaussianNB()
naive_risco_credito.fit(x_base_risco_credito,y_base_risco_credito)

GaussianNB()

In [22]:
previsao = naive_risco_credito.predict([[0, 0, 1, 2],[2, 0, 0 , 0]])

In [23]:
previsao

array(['baixo', 'moderado'], dtype='<U8')

In [24]:
naive_risco_credito.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [25]:
naive_risco_credito.class_count_

array([6., 5., 3.])

In [31]:
naive_risco_credito.class_prior_

array([0.42857143, 0.35714286, 0.21428571])